#!/bin/bash
INTERVAL=1000000
SIMTIME=10000000
MODE=4
LOSS_MODEL=2
RETRANSMISSION=0

echo "Parameters: Interval Mode Simtime PathLossModel Retransmission" >> bash_export_exp6_no_retransmission.txt
echo $INTERVAL $MODE $SIMTIME $LOSS_MODEL $RETRANSMISSION >> bash_export_exp6_no_retransmission.txt

for i in {1..2001..10}
        do
                echo -n $i ", "
                python loraDir.py $i $INTERVAL $MODE $SIMTIME $LOSS_MODEL $RETRANSMISSION | grep "DER:"  | cut -d: -f2 | sed "s/ //" >> bash_export_exp6_no_retransmission.txt
        done
echo "work done" >> bash_export_exp6_no_retransmission.txt
