#!/bin/bash
INTERVAL=1000000
SIMTIME=10000000
MODE=4
LOSS_MODEL=2
RETRANSMISSION=0

echo "Parameters: Interval Mode Simtime PathLossModel Retransmission" >> bash_export_exp6_retransmissions_schemes.txt
echo $INTERVAL $MODE $SIMTIME $LOSS_MODEL $RETRANSMISSION >> bash_export_exp6_retransmissions_schemes.txt

for i in {1..2501..100}
        do
                echo -n $i ", "
                python loraDir.py $i $INTERVAL $MODE $SIMTIME $LOSS_MODEL $RETRANSMISSION | grep "DER:"  | cut -d: -f2 | sed "s/ //" >> bash_export_exp6_retransmissions_schemes.txt
        done
echo "work done" >> bash_export_exp6_retransmissions_schemes.txt

RETRANSMISSION=1

echo "Parameters: Interval Mode Simtime PathLossModel Retransmission" >> bash_export_exp6_retransmissions_schemes.txt
echo $INTERVAL $MODE $SIMTIME $LOSS_MODEL $RETRANSMISSION >> bash_export_exp6_retransmissions_schemes.txt

for i in {1..2501..100}
        do
                echo -n $i ", "
                python loraDir.py $i $INTERVAL $MODE $SIMTIME $LOSS_MODEL $RETRANSMISSION | grep "DER:"  | cut -d: -f2 | sed "s/ //" >> bash_export_exp6_retransmissions_schemes.txt
        done
echo "work done" >> bash_export_exp6_retransmissions_schemes.txt

RETRANSMISSION=2

echo "Parameters: Interval Mode Simtime PathLossModel Retransmission" >> bash_export_exp6_retransmissions_schemes.txt
echo $INTERVAL $MODE $SIMTIME $LOSS_MODEL $RETRANSMISSION >> bash_export_exp6_retransmissions_schemes.txt

for i in {1..2501..100}
        do
                echo -n $i ", "
                python loraDir.py $i $INTERVAL $MODE $SIMTIME $LOSS_MODEL $RETRANSMISSION | grep "DER:"  | cut -d: -f2 | sed "s/ //" >> bash_export_exp6_retransmissions_schemes.txt
        done
echo "work done" >> bash_export_exp6_retransmissions_schemes.txt

RETRANSMISSION=3

echo "Parameters: Interval Mode Simtime PathLossModel Retransmission" >> bash_export_exp6_retransmissions_schemes.txt
echo $INTERVAL $MODE $SIMTIME $LOSS_MODEL $RETRANSMISSION >> bash_export_exp6_retransmissions_schemes.txt

for i in {1..2501..100}
        do
                echo -n $i ", "
                python loraDir.py $i $INTERVAL $MODE $SIMTIME $LOSS_MODEL $RETRANSMISSION | grep "DER:"  | cut -d: -f2 | sed "s/ //" >> bash_export_exp6_retransmissions_schemes.txt
        done
echo "work done" >> bash_export_exp6_retransmissions_schemes.txt